spring.application.name=ku-ku-app

server.port= 8083


# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Database Configuration
spring.datasource.url=jdbc:mysql://yo-yo-db.c94ic80yckln.eu-north-1.rds.amazonaws.com:3306/ku-ku-db
spring.datasource.username=root
spring.datasource.password=Root4321Root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email, openid

