spring.application.name=ku-ku-app

# Render dynamic port support
server.port=${PORT:8080}

# Allow external traffic (VERY IMPORTANT for Docker/Render)
server.address=0.0.0.0

# ===============================
# Performance (recommended)
# ===============================

# REMOVE or set to false — lazy init delays JPA/Hibernate setup unpredictably
spring.main.lazy-initialization=false

# Disable unnecessary open session
spring.jpa.open-in-view=false


# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html



# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update



# JWT Configuration
app.jwt.secret=mySecretKey1234567890123456789012345678901234567890
app.jwt.expiration=86400000
app.jwt.refresh.expiration=604800000


# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email, openid

spring.security.oauth2.client.registration.google.redirect-uri=https://tuk-tuk-backend-wvi2.onrender.com/login/oauth2/code/google


# Provider settings
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v2/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=email





